---
abstract: 'A very simplistic workflow framework'
author:
  - 'jason hord <pravus@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Workflow-Lite
no_index:
  directory:
    - inc
    - t
requires:
  Class::MOP: 0
  Moose: 0
  Moose::Exporter: 0
  Moose::Role: 0
  MooseX::ClassAttribute: 0
  namespace::autoclean: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.05
